env:
  - distro: centos7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume =/ sys/ fs/ cgroup:/ sys/ fs/ cgroup:r\ o"
  - distro: debian8
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume =/ sys/ fs/ cgroup:/ sys/ fs/ cgroup:r\ o"

before_install:
  - 'docker pull geerlingguy/docker-${distro}-ansible:latest'

script:
#start docker container
  - container_id=$(mktemp)
  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/ansible-role-mosquitto:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'
# check syntax
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/ansible-role-mosquitto/tests/test.yml --syntax-check'
# check first run does not fail
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/ansible-role-mosquitto/tests/test.yml'
# Run the role/ playbook again, checking to make sure it's idempotent.
  - idempotence=$(mktemp)
  - 'docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/ansible-role-mosquitto/tests/test.yml | tee -a ${idempotence}'
  - 'tail ${idempotence} | grep -q "changed=0.*failed=0" && (echo "Idempotence test: pass" && exit 0) || (echo "Idempotence test: fail" && exit 1)'
