---

- include_tasks: centOS.yml
  when: ansible_os_family == "RedHat"

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Copy config files
  copy:
    src: '{{ item }}'
    dest: /etc/mosquitto/conf.d
  with_items:
    - websocket.conf
    - default.conf

- name: Make sure mosquitto is started and enabled to start on boot
  systemd:
    name: 'mosquitto'
    state: 'started'
    enabled: 'yes'
